
version: '3.1'

services:

  db:
    platform: linux/x86_64
    image: mysql:5.7
    container_name: app_db
    command: --default-authentication-plugin=mysql_native_password
    restart: always
    environment:
      MYSQL_ROOT_PASSWORD: ${DOCKER_DATASOURCE_PASSWORD}
    ports:
      - 3307:3306
      